#!/bin/bash

pgrep -x dmenu && exit

# Some functions for handling the work
choose-and-start() {
	CHOSEN_CONF="$(printf '%s\n' "${CONFIGS[@]}" | dmenu -i -p "Which OpenVPN config?")"
	[ -z "$CHOSEN_CONF" ] && exit 1

	sudo rc-service openvpn.${CHOSEN_CONF} start
}

stop-all() {
	for vpn in ${CONFIGS[@]}; do
		sudo rc-service openvpn.${vpn} stop
	done
}

# The (file)names of the configuration
declare -a CONFIGS

# Find all configuration files:
for file in `ls /etc/openvpn/*.conf`; do
	CONFIGS+=($(basename "${file%.*}"))
done

# Check if any VPN is connected
if [ -d '/sys/class/net/tun0' ]; then
	# Check if script has been invoked by mouse click
	case $BLOCK_BUTTON in
		1) echo "stopping..."; stop-all ;;
	esac

	# If so, print IP address
	ip addr show dev tun0 | grep 'inet ' | awk '{print $2}' | awk -F '/' '{print $1}'
else
	# Check if script has been invoked by mouse click
	case $BLOCK_BUTTON in
		1) echo "starting..."; choose-and-start ;;
	esac

	# If not connected, show X emoji
	echo "❌"
fi

