#!/bin/sh
# A rofi -dmenu prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Drives mounted at /, /boot and /home will not be options to unmount.
# This can be changed by modifying the awk command in $drives.
COLS="name,type,size,mountpoint"
export SUDO_ASKPASS='/usr/lib/ssh/ssh-askpass'

drives=$(lsblk -rpo "$COLS" | awk '$2=="part"&&$4!~/boot|home|SWAP/&&length($4)>1{printf "%s (%s) on %s\n",$1,$3,$4}')
[ -z "$drives" ] && exit

chosen=$(echo "$drives" | rofi -dmenu -i -p "Unmount which drive?" | awk '{print $1}')
[ -z "$chosen" ] && exit

sudo -A umount "$chosen" && notify-send "$chosen unmounted."

